# Generated by Django 5.1.2 on 2024-10-26 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros_api', '0002_alter_livro_estaemprestado_alter_livro_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebedor', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateField()),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros_api.livro')),
            ],
        ),
    ]
